
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mucha
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDashboard = new javax.swing.JLabel();
        jLabelSecurity = new javax.swing.JLabel();
        jLabelSchedule = new javax.swing.JLabel();
        jLabelSecurityPost = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabelDashboard.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDashboard.setText("Dashboard");
        jLabelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDashboardMouseClicked(evt);
            }
        });

        jLabelSecurity.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelSecurity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSecurity.setText("Security");
        jLabelSecurity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSecurity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSecurityMouseClicked(evt);
            }
        });

        jLabelSchedule.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelSchedule.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSchedule.setText("Schedule");
        jLabelSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelScheduleMouseClicked(evt);
            }
        });

        jLabelSecurityPost.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelSecurityPost.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSecurityPost.setText("Security Post");
        jLabelSecurityPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSecurityPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSecurityPostMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSecurity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSchedule, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSecurityPost)
                    .addComponent(jLabelDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabelDashboard)
                .addGap(18, 18, 18)
                .addComponent(jLabelSecurity)
                .addGap(18, 18, 18)
                .addComponent(jLabelSchedule)
                .addGap(18, 18, 18)
                .addComponent(jLabelSecurityPost)
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSecurityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSecurityMouseClicked
        // TODO add your handling code here:
        dispose();
        
        DataSecurity dataSecurity = new DataSecurity();
        dataSecurity.setVisible(true);
    }//GEN-LAST:event_jLabelSecurityMouseClicked

    private void jLabelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashboardMouseClicked
        // TODO add your handling code here:
        
       dispose();
       DashboardAdmin dashboardAdmin = new DashboardAdmin();
       dashboardAdmin.setVisible(true);
    }//GEN-LAST:event_jLabelDashboardMouseClicked

    private void jLabelScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelScheduleMouseClicked
        // TODO add your handling code here:
        dispose();
        Schedule schedule = new Schedule();
        schedule.setVisible(true);
                
    }//GEN-LAST:event_jLabelScheduleMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int result = 0;
        result = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin?","LOGOUT" ,result );
        if(result == 0){
            dispose();
        
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelSecurityPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSecurityPostMouseClicked
        // TODO add your handling code here:
        dispose();
        SecurityPost securityPost = new SecurityPost();
        securityPost.setVisible(true);
                
    }//GEN-LAST:event_jLabelSecurityPostMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
//    Utils
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelSchedule;
    private javax.swing.JLabel jLabelSecurity;
    private javax.swing.JLabel jLabelSecurityPost;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
